[theme]
base="light"
primaryColor="#CC0000"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8f9fa"
textColor="#0d0d0d"
font="sans serif"

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
